export const TYPES = {
  RootStore: Symbol.for('RootStore'),
  NetworkStore: Symbol.for('NetworkStore'),
  SyncCoordinator: Symbol.for('SyncCoordinator'),
  WatermelonDatabase: Symbol.for('WatermelonDatabase'),
  WatermelonManager: Symbol.for('WatermelonManager'),
  HttpManager: Symbol.for('HttpManager'),
  TaskService: Symbol.for('TaskService'),
  TaskRepository: Symbol.for('TaskRepository'),
  GetAllTasksUseCase: Symbol.for('GetAllTasksUseCase'),
  GetTaskByIdUseCase: Symbol.for('GetTaskByIdUseCase'),
  ObserveTasksUseCase: Symbol.for('ObserveTasksUseCase'),
  SyncTasksUseCase: Symbol.for('SyncTasksUseCase'),
  ToggleTaskCompletedUseCase: Symbol.for('ToggleTaskCompletedUseCase'),
  UpdateTaskAttachmentUseCase: Symbol.for('UpdateTaskAttachmentUseCase'),
  HomeViewModel: Symbol.for('HomeViewModel'),
  TaskDetailViewModel: Symbol.for('TaskDetailViewModel'),
  CameraPermissionsViewModel: Symbol.for('CameraPermissionsViewModel'),
} as const;
